services:
  web:
    image: ghcr.io/dekkmarsvin/auth-web:latest
    ports:
      - 4000:80
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --tries=1 --no-verbose http://localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/dekkmarsvin/auth-api:latest
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - REFRESH_TOKEN_SECRET
      - ACCESS_TOKEN_SECRET
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - RDB_HOST=redis
      - RDB_PORT=6379
      - MAILGUN_DOMAIN
      - MAILGUN_APIKEY
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --tries=1 --no-verbose http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgresql:
    image: postgres:17.7-alpine3.23
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=auth
      - POSTGRES_DB=auth
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.5
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  default:
    name: auth
    driver: bridge
